# docker-compose up --build --pull always

services:
  ollama:
    image: ollama/ollama
    network_mode: "host"
    ports:
      - 11434:11434
    restart: on-failure
    volumes:
      - /Users/bam/.ollama/models:/root/.ollama/models  # Mount local models directory
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.25.10
    ports:
      - 8080:8080
      - 3000:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'e'
      CLUSTER_HOSTNAME: 'node1'
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - PORT=9090
      - DATABASE_URL=://weaviate:8080 # Add database connection string
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - weaviate  # Ensure the database starts first
volumes:
  open-webui:
  weaviate_data:  # Persistent volume for database data