# docker-compose up --build --pull always

services:
  ollama:
    image: ollama/ollama
    network_mode: "host"
    ports:
      - 11434:11434
    restart: on-failure
    volumes:
      - /Users/bam/.ollama/models:/root/.ollama/models  # Mount local models directory


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - PORT=9090
      - WEAVIATE_HOST=http://localhost:8080  # Weaviate host address
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 9090:9090
    restart: always

volumes:
  open-webui:
